ALTER SESSION SET NLS_LANGUAGE = 'AMERICAN';
--------------------------------------------------------------------------------------------------------------------------
------------------------------------- ƒ»¿œ¿«ŒÕÕŒ≈ —≈ ÷»ŒÕ»–Œ¬¿Õ»≈ --------------------------------------------------------
CREATE TABLESPACE TS_RANGE1
DATAFILE 'C:\database_labs\tablepaces\TS_RANGE1.DBF'
SIZE 1M
AUTOEXTEND ON NEXT 1K
MAXSIZE 2M
EXTENT MANAGEMENT LOCAL;

CREATE TABLESPACE TS_RANGE2
DATAFILE 'C:\database_labs\tablepaces\TS_RANGE2.DBF'
SIZE 1M
AUTOEXTEND ON NEXT 1K
MAXSIZE 2M
EXTENT MANAGEMENT LOCAL;

CREATE TABLESPACE TS_RANGE3
DATAFILE 'C:\database_labs\tablepaces\TS_RANGE3.DBF'
SIZE 1M
AUTOEXTEND ON NEXT 1K
MAXSIZE 2M
EXTENT MANAGEMENT LOCAL;

ALTER DATABASE DATAFILE 'C:\database_labs\tablepaces\TS_RANGE1.DBF' RESIZE 40M;
ALTER DATABASE DATAFILE 'C:\database_labs\tablepaces\TS_RANGE2.DBF' RESIZE 40M;
ALTER DATABASE DATAFILE 'C:\database_labs\tablepaces\TS_RANGE3.DBF' RESIZE 40M;


CREATE TABLE KDV.T_RANGE (X NUMBER, Y NUMBER, Z NUMBER)
PARTITION BY RANGE(X)
(
    PARTITION RANGE_3 VALUES LESS THAN (30) TABLESPACE TS_RANGE3,
    PARTITION RANGE_2 VALUES LESS THAN (60) TABLESPACE TS_RANGE2,
    PARTITION RANGE_1 VALUES LESS THAN (90) TABLESPACE TS_RANGE1
);

ALTER USER KDV QUOTA UNLIMITED ON TS_RANGE1;
ALTER USER KDV QUOTA UNLIMITED ON TS_RANGE2;
ALTER USER KDV QUOTA UNLIMITED ON TS_RANGE3;

SELECT * FROM USER_TAB_PARTITIONS WHERE TABLE_NAME = 'T_RANGE';
INSERT INTO KDV.T_RANGE VALUES(10,10,10);
INSERT INTO KDV.T_RANGE VALUES(40,40,40);
INSERT INTO KDV.T_RANGE VALUES(70,70,70);

SELECT * FROM KDV.T_RANGE PARTITION FOR(0)
UNION
SELECT * FROM KDV.T_RANGE PARTITION FOR(50)
UNION
SELECT * FROM KDV.T_RANGE PARTITION FOR(60);
SELECT * FROM KDV.T_RANGE;

--------------------------------------------------------------------------------------------------------------------------
------------------------------------- »Õ“≈–¬¿À‹ÕŒ≈ —≈ ÷»ŒÕ»–Œ¬¿Õ»≈ --------------------------------------------------------
CREATE TABLE T_INTERVAL (DATE_ DATE, Y NUMBER, Z NUMBER)
PARTITION BY RANGE (DATE_)
INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
(
    PARTITION P0 VALUES LESS THAN (TO_DATE('1-1-2006', 'DD-MM-YYYY')),
    PARTITION P1 VALUES LESS THAN (TO_DATE('1-1-2007', 'DD-MM-YYYY')),
    PARTITION P2 VALUES LESS THAN (TO_DATE('1-7-2009', 'DD-MM-YYYY'))
) TABLESPACE LABS;

INSERT INTO T_INTERVAL VALUES('20-1-2006',1,1);
INSERT INTO T_INTERVAL VALUES('30-1-2007',1,1);
INSERT INTO T_INTERVAL VALUES('15-7-2009',1,1);


SELECT * FROM T_INTERVAL PARTITION FOR ('1-1-2006')
UNION
SELECT * FROM T_INTERVAL PARTITION FOR ('1-1-2007')
UNION
SELECT * FROM T_INTERVAL PARTITION FOR ('1-7-2009');
SELECT * FROM T_INTERVAL;

SELECT * FROM USER_TAB_PARTITIONS WHERE TABLE_NAME = 'T_INTERVAL';


--------------------------------------------------------------------------------------------------------------------------
------------------------------------- ’≈ÿ-—≈ ÷»ŒÕ»–Œ¬¿Õ»≈ --------------------------------------------------------
CREATE TABLESPACE TS_HASH1
DATAFILE 'C:\database_labs\tablepaces\TS_HASH1.DBF'
SIZE 1M
AUTOEXTEND ON NEXT 1K
MAXSIZE 2M
EXTENT MANAGEMENT LOCAL;

CREATE TABLESPACE TS_HASH2
DATAFILE 'C:\database_labs\tablepaces\TS_HASH2.DBF'
SIZE 1M
AUTOEXTEND ON NEXT 1K
MAXSIZE 2M
EXTENT MANAGEMENT LOCAL;

CREATE TABLESPACE TS_HASH3
DATAFILE 'C:\database_labs\tablepaces\TS_HASH3.DBF'
SIZE 1M
AUTOEXTEND ON NEXT 1K
MAXSIZE 2M
EXTENT MANAGEMENT LOCAL;

ALTER DATABASE DATAFILE 'C:\database_labs\tablepaces\TS_HASH1.DBF' RESIZE 10M;
ALTER DATABASE DATAFILE 'C:\database_labs\tablepaces\TS_HASH2.DBF' RESIZE 10M;
ALTER DATABASE DATAFILE 'C:\database_labs\tablepaces\TS_HASH3.DBF' RESIZE 10M;

ALTER USER KDV QUOTA UNLIMITED ON TS_HASH1;
ALTER USER KDV QUOTA UNLIMITED ON TS_HASH2;
ALTER USER KDV QUOTA UNLIMITED ON TS_HASH3;

CREATE TABLE T_HASH (X VARCHAR2(10), Y NUMBER, Z NUMBER)
PARTITION BY HASH (X)
PARTITIONS 4
STORE IN (TS_HASH1, TS_HASH2, TS_HASH3);

SELECT * FROM USER_TAB_PARTITIONS;
INSERT INTO T_HASH VALUES('VARCHAR2', 5, 5);
INSERT INTO T_HASH VALUES('NOTCHAR', 12, 12);
INSERT INTO T_HASH VALUES('LIKECHAR', 16, 16);

SELECT * FROM T_HASH;

SELECT * FROM T_HASH PARTITION FOR ('VARCHAR2')
UNION
SELECT * FROM T_HASH PARTITION FOR ('NOTCHAR')
UNION
SELECT * FROM T_HASH PARTITION FOR ('LIKECHAR');


--------------------------------------------------------------------------------------------------------------------------
------------------------------------- —œ»—Œ◊ÕŒ≈ —≈ ÷»ŒÕ»–Œ¬¿Õ»≈ --------------------------------------------------------
CREATE TABLESPACE TS_LIST1
DATAFILE 'C:\database_labs\tablepaces\TS_LIST1.DBF'
SIZE 1M
AUTOEXTEND ON NEXT 1K
MAXSIZE 2M
EXTENT MANAGEMENT LOCAL;

CREATE TABLESPACE TS_LIST2
DATAFILE 'C:\database_labs\tablepaces\TS_LIST2.DBF'
SIZE 1M
AUTOEXTEND ON NEXT 1K
MAXSIZE 2M
EXTENT MANAGEMENT LOCAL;

CREATE TABLESPACE TS_LIST3
DATAFILE 'C:\database_labs\tablepaces\TS_LIST3.DBF'
SIZE 1M
AUTOEXTEND ON NEXT 1K
MAXSIZE 2M
EXTENT MANAGEMENT LOCAL;

ALTER DATABASE DATAFILE 'C:\database_labs\tablepaces\TS_LIST1.DBF' RESIZE 10M;
ALTER DATABASE DATAFILE 'C:\database_labs\tablepaces\TS_LIST2.DBF' RESIZE 10M;
ALTER DATABASE DATAFILE 'C:\database_labs\tablepaces\TS_LIST3.DBF' RESIZE 10M;

ALTER USER KDV QUOTA UNLIMITED ON TS_LIST1;
ALTER USER KDV QUOTA UNLIMITED ON TS_LIST2;
ALTER USER KDV QUOTA UNLIMITED ON TS_LIST3;




CREATE TABLE T_LIST (X CHAR(3), Y NUMBER, Z NUMBER) 
PARTITION BY LIST(X)
(
    PARTITION NORTHEAST_SALES VALUES('NYC', 158, 130) TABLESPACE TS_LIST1,
    PARTITION SOUTHEAST_SALES VALUES('MYC', 38, 33) TABLESPACE TS_LIST2,
    PARTITION WESTNORTH_SALES VALUES('SAN', 107, 48) TABLESPACE TS_LIST3
);
SELECT * FROM T_LIST PARTITION FOR ('NYC')
UNION
SELECT * FROM T_LIST PARTITION FOR ('MYC')
UNION
SELECT * FROM T_LIST PARTITION FOR ('SAN');

INSERT INTO T_LIST VALUES('NYC', 158, 130);
INSERT INTO T_LIST VALUES('MYC', 38, 33);
INSERT INTO T_LIST VALUES('SAN', 107, 48);

-----------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------
ALTER TABLE T_LIST ENABLE ROW MOVEMENT;
ALTER TABLE T_RANGE ENABLE ROW MOVEMENT;
ALTER TABLE T_INTERVAL ENABLE ROW MOVEMENT;
ALTER TABLE T_HASH ENABLE ROW MOVEMENT;


UPDATE T_LIST SET X = 'SAN' WHERE X = 'NYC'; 
UPDATE T_LIST SET X = 'NYC' WHERE X = 'SAN'; 

SELECT * FROM T_LIST PARTITION FOR ('NYC')
UNION
SELECT * FROM T_LIST PARTITION FOR ('MYC')
UNION
SELECT * FROM T_LIST PARTITION FOR ('SAN');

UPDATE T_RANGE SET X = X+50 WHERE X = 10; 
UPDATE T_RANGE SET X = 10 WHERE X = 60;

SELECT * FROM KDV.T_RANGE PARTITION FOR(0)
UNION
SELECT * FROM KDV.T_RANGE PARTITION FOR(50)
UNION
SELECT * FROM KDV.T_RANGE PARTITION FOR(60);

UPDATE T_INTERVAL SET X = TO_DATE('20.1.2007', 'DD-MM-YYYY') WHERE X = TO_DATE('20.1.2006', 'DD-MM-YYYY');
UPDATE T_INTERVAL SET X = '20-01-2006' WHERE X = '20-01-2007'; 

SELECT * FROM T_INTERVAL PARTITION FOR ('1-1-2006')
UNION
SELECT * FROM T_INTERVAL PARTITION FOR ('1-1-2007')
UNION
SELECT * FROM T_INTERVAL PARTITION FOR ('1-7-2009');

UPDATE T_HASH SET X = 'VARCHAR2' WHERE X = 'LIKECHAR'; 
UPDATE T_HASH SET X = 'LIKECHAR' WHERE X = 'VARCHAR2'; 

SELECT * FROM T_HASH PARTITION FOR ('VARCHAR2')
UNION
SELECT * FROM T_HASH PARTITION FOR ('NOTCHAR')
UNION
SELECT * FROM T_HASH PARTITION FOR ('LIKECHAR');


--------------------------------------------------------------------------------------------------------------------------
------------------------------------- ALTER TABLE MERGEl --------------------------------------------------------

ALTER TABLE T_RANGE SPLIT PARTITION RANGE_3 AT (0)
INTO(
    PARTITION sp_1 TABLESPACE TS_RANGE1,
    PARTITION sp_2 TABLESPACE TS_RANGE2
);
SELECT * FROM T_RANGE PARTITION FOR (0);
SELECT * FROM T_RANGE;
INSERT INTO T_RANGE VALUES(0,0,0);
--------------------------------------------------------------------------------------------------------------------------
------------------------------------- ALTER TABLE SPLIT--------------------------------------------------------


ALTER TABLE T_LIST MERGE PARTITIONS NORTHEAST_SALES, SOUTHEAST_SALES INTO PARTITION P0;

--------------------------------------------------------------------------------------------------------------------------
------------------------------------- ALTER TABLE EXCHANGE --------------------------------------------------------
CREATE TABLE TT(DATE_ DATE, Y NUMBER, Z NUMBER);
DROP TABLE TT;
ALTER TABLE T_INTERVAL EXCHANGE PARTITION P0 WITH TABLE TT;
SELECT * FROM TT;


SELECT * FROM USER_TAB_PARTITIONS;
SELECT * FROM DBA_TAB_PARTITIONS;