CREATE DATABASE LINK conToIvan
CONNECT TO GISCORE1
IDENTIFIED BY Dfyef2001
using 'ServerDB1:1521/orcl';
DROP DATABASE LINK conToIvan;
SELECT * FROM LAB14@conToIvan;
INSERT INTO LAB14@conToIvan VALUES(1,2);
UPDATE LAB14@conToIvan set x = 4;
DELETE LAB14@conToIvan where y = 2;
CREATE OR REPLACE PROCEDURE PLUS(X NUMBER,Y NUMBER)
is
BEGIN
    INSERT INTO LAB14@conToIvan values(X+Y,Y+X);
    COMMIT;
END;
CREATE OR REPLACE FUNCTION MINUS_(X NUMBER,Y NUMBER)return NUMBER
is
BEGIN
    INSERT INTO LAB14@conToIvan values(X-Y,Y-X);
    COMMIT;
    RETURN X-Y;
END;
EXEC PLUS(7,9);
DECLARE 
 RES NUMBER:=MINUS_(5,12);
BEGIN 
 DBMS_OUTPUT.PUT_LINE(RES);
END;
commit;
--LAB14(X,Y)

CREATE DATABASE LINK conToIvan
CONNECT TO GISCORE1
IDENTIFIED BY Dfyef2001
using 'ServerDB1:1521/orcl';

CREATE PUBLIC DATABASE LINK publicIvan
CONNECT TO GISCORE1
IDENTIFIED BY Dfyef2001
using 'ServerDB1:1521/orcl';
DROP PUBLIC DATABASE LINK publicIvan;
SELECT * FROM LAB14@publicIvan;




INSERT INTO LAB14@publicIvan VALUES(1,2);
UPDATE LAB14@publicIvan set x = 4;
DELETE LAB14@publicIvan where y = 2;
CREATE OR REPLACE PROCEDURE PLUS_(X NUMBER,Y NUMBER)
is
BEGIN
    INSERT INTO LAB14@publicIvan values(X+Y,Y+X);
    COMMIT;
END;
CREATE OR REPLACE FUNCTION MINUS__(X NUMBER,Y NUMBER)return NUMBER
is
BEGIN
    INSERT INTO LAB14@publicIvan values(X-Y,Y-X);
    COMMIT;
    RETURN X-Y;
END;
EXEC PLUS(7,9);
DECLARE 
 RES NUMBER:=MINUS__(5,12);
BEGIN 
 DBMS_OUTPUT.PUT_LINE(RES);
END;
commit;
