CREATE USER USLK IDENTIFIED BY DVVVV
DEFAULT TABLESPACE LABS QUOTA UNLIMITED ON LABS
ACCOUNT UNLOCK;
GRANT CREATE SESSION,
SELECT ANY TABLE, 
CREATE TABLE TO USLK;
DROP USER USLK;
SELECT * FROM V$TABLESPACE;
SELECT * FROM TEACHER;
SELECT * FROM dba_tables where tablespace_name = 'LABS';
GRANT DROP PUBLIC DATABASE LINK TO KDV;